export enum Paths {
	HOME = "/",
	LOGIN = "/login",
	LOGOUT = "/logout",
	SIGNUP = "/signup",
	TODO = "/todo",
	ADD_TODO = "/add-todo",
	EDIT_TODO = "/todo/edit-todo/:todoId",
	APPOINTMENT = "/appointment",
	ADD_APPOINTMENT = "/add-appointment",
	EDIT_APPOINTMENT = "/edit-appointment",
	CONTACT = "/contact",
	ABOUT = "/about-us",
	USER_PROFILE = "/user-profile",
	RECOVER_PASSWORD = "/recover-password",
	RESET_PASSWORD = "/reset-password",
	CREATE_PATIENT = "/create-patient",
	PATIENT_DETAILS = "/patient-details",
	ERROR = "*",
}
