export enum Paths {
	HOME = "/",
	LOGIN = "/login",
	LOGOUT = "/logout",
	SIGNUP = "/signup",
	TODO = "/todo",
	ADD_TODO = "/add-todo",
	EDIT_TODO = "/edit-todo/:id",
	APPOINTMENT = "/appointment",
	ADD_APPOINTMENT = "/add-appointment",
	EDIT_APPOINTMENT = "/edit-appointment",
	CONTACT = "/contact",
	ABOUT = "/about-us",
	RECOVER_PASSWORD = "/recover-password",
	RESET_PASSWORD = "/reset-password",
	ERROR = "*",
}
